export const SVG_NS = 'http://www.w3.org/2000/svg';
export const XLINK_NS = 'http://www.w3.org/1999/xlink';

export const AWS_ICON_PATHS = {
    EC2: 'icons/ec2.svg',
    EKS: 'icons/eks.svg',
    ECS: 'icons/ecs.svg',
    Lambda: 'icons/lambda.svg',
    ASG: 'icons/autoscaling.svg',
    ECR: 'icons/ecr.svg',
    VPC: 'icons/vpc.svg',
    Subnet: 'icons/subnet.svg',
    IGW: 'icons/igw.svg',
    NAT: 'icons/nat.svg',
    EIP: 'icons/eip.svg',
    RDS: 'icons/rds.svg',
    DDB: 'icons/dynamodb.svg',
    Cache: 'icons/elasticache.svg',
    S3: 'icons/s3.svg',
    ALB: 'icons/alb.svg',
    NLB: 'icons/nlb.svg',
    TG: 'icons/tg.svg',
    SG: 'icons/sg.svg',
    IAM: 'icons/iam.svg',
    KMS: 'icons/kms.svg',
    WAF: 'icons/waf.svg',
    CF: 'icons/cloudfront.svg',
    R53: 'icons/route53.svg',
    SQS: 'icons/sqs.svg',
    SNS: 'icons/sns.svg',
    CW: 'icons/cloudwatch.svg',
    Docker: 'icons/docker.svg',
};

export const RESOURCE_CATEGORIES = {
    vpc: { match: ['aws_vpc', 'aws_default_vpc'], color: '#118ab2', label: 'VPC', icon: 'VPC' },
    subnet: { match: ['aws_subnet'], color: '#073b4c', label: 'Subnet', icon: 'Subnet' },
    instance: { match: ['aws_instance', 'aws_launch_template'], color: '#ff6b35', label: 'EC2', icon: 'EC2' },
    eks: { match: ['aws_eks_cluster', 'aws_eks_node_group'], color: '#ff6b35', label: 'EKS', icon: 'EKS' },
    ecs: { match: ['aws_ecs_cluster', 'aws_ecs_service', 'aws_ecs_task_definition'], color: '#ff6b35', label: 'ECS', icon: 'ECS' },
    lambda: { match: ['aws_lambda_function'], color: '#ff6b35', label: 'Lambda', icon: 'Lambda' },
    rds: { match: ['aws_db_instance', 'aws_rds_cluster'], color: '#ef476f', label: 'RDS', icon: 'RDS' },
    dynamodb: { match: ['aws_dynamodb_table'], color: '#ef476f', label: 'DynamoDB', icon: 'DDB' },
    elasticache: { match: ['aws_elasticache_cluster', 'aws_elasticache_replication_group'], color: '#ef476f', label: 'ElastiCache', icon: 'Cache' },
    s3: { match: ['aws_s3_bucket'], color: '#ffd166', label: 'S3', icon: 'S3' },
    alb: { match: ['aws_alb'], color: '#06d6a0', label: 'ALB', icon: 'ALB' },
    nlb: { match: [], color: '#06d6a0', label: 'NLB', icon: 'NLB' },
    tg: { match: ['aws_lb_target_group', 'aws_alb_target_group'], color: '#06d6a0', label: 'Target Group', icon: 'TG' },
    sg: { match: ['aws_security_group'], color: '#8338ec', label: 'Security Group', icon: 'SG' },
    iam_role: { match: ['aws_iam_role'], color: '#8338ec', label: 'IAM Role', icon: 'IAM' },
    route53: { match: ['aws_route53_zone', 'aws_route53_record'], color: '#8338ec', label: 'Route 53', icon: 'R53' },
    cloudfront: { match: ['aws_cloudfront_distribution'], color: '#8338ec', label: 'CloudFront', icon: 'CF' },
    sqs: { match: ['aws_sqs_queue'], color: '#e07a5f', label: 'SQS', icon: 'SQS' },
    sns: { match: ['aws_sns_topic'], color: '#e07a5f', label: 'SNS', icon: 'SNS' },
    ecr: { match: ['aws_ecr_repository'], color: '#ff6b35', label: 'ECR', icon: 'ECR' },
    nat: { match: ['aws_nat_gateway'], color: '#118ab2', label: 'NAT GW', icon: 'NAT' },
    igw: { match: ['aws_internet_gateway'], color: '#118ab2', label: 'IGW', icon: 'IGW' },
    eip: { match: ['aws_eip'], color: '#118ab2', label: 'Elastic IP', icon: 'EIP' },
    kms: { match: ['aws_kms_key'], color: '#8338ec', label: 'KMS', icon: 'KMS' },
    cloudwatch: { match: ['aws_cloudwatch_log_group', 'aws_cloudwatch_metric_alarm'], color: '#e07a5f', label: 'CloudWatch', icon: 'CW' },
    autoscaling: { match: ['aws_autoscaling_group'], color: '#ff6b35', label: 'ASG', icon: 'ASG' },
    waf: { match: ['aws_wafv2_web_acl'], color: '#8338ec', label: 'WAF', icon: 'WAF' },
};

export const CATEGORY_GROUPS = {
    INTERNET: new Set(['igw', 'cloudfront', 'route53', 'waf']),
    INGRESS: new Set(['alb', 'nlb', 'tg']),
    DATA: new Set(['rds', 'dynamodb', 'elasticache', 's3']),
    MESSAGING: new Set(['sqs', 'sns']),
    SECURITY: new Set(['sg', 'iam_role', 'kms', 'cloudwatch']),
    VPC: new Set(['vpc']),
    SUBNET: new Set(['subnet']),
};

export const STAT_CATEGORY_MAP = {
    vpc: ['vpc', 'subnet', 'nat', 'igw', 'eip'],
    compute: ['instance', 'eks', 'ecs', 'lambda', 'ecr', 'autoscaling'],
    db: ['rds', 'dynamodb', 'elasticache'],
    storage: ['s3'],
    lb: ['alb', 'nlb', 'tg'],
};

export const SVG_LAYOUT = {
    NW: 120,
    NH: 76,
    NGX: 20,
    NGY: 16,
    ICON_S: 34,
    CP: 40,
    VPC_LBL: 34,
    VPC_PAD: 22,
    SUB_LBL: 26,
    SUB_PAD: 14,
    SUB_GAP: 12,
    ZONE_GAP: 20,
    SEC_GAP: 20,
    maxIngressCols: 6,
    maxDataCols: 6,
    maxOtherCols: 4,
    maxInternetCols: 6,
    maxMessagingCols: 6,
    maxSubnetCols: 3,
};

export const DRAWIO_LAYOUT = {
    NW: 78,
    NH: 78,
    NGX: 32,
    NGY: 32,
    ICON_S: 0,
    CP: 50,
    VPC_LBL: 60,
    VPC_PAD: 40,
    SUB_LBL: 50,
    SUB_PAD: 28,
    SUB_GAP: 16,
    ZONE_GAP: 40,
    SEC_GAP: 40,
    maxIngressCols: 5,
    maxDataCols: 5,
    maxOtherCols: 4,
    maxInternetCols: 6,
    maxMessagingCols: 5,
    maxSubnetCols: 3,
};
