export const SVG_NS = 'http://www.w3.org/2000/svg';
export const XLINK_NS = 'http://www.w3.org/1999/xlink';

export const ICON_PATHS = {
    // AWS
    EC2: 'icons/ec2.svg',
    EKS: 'icons/eks.svg',
    ECS: 'icons/ecs.svg',
    Lambda: 'icons/lambda.svg',
    ASG: 'icons/autoscaling.svg',
    ECR: 'icons/ecr.svg',
    VPC: 'icons/vpc.svg',
    Subnet: 'icons/subnet.svg',
    IGW: 'icons/igw.svg',
    NAT: 'icons/nat.svg',
    EIP: 'icons/eip.svg',
    RDS: 'icons/rds.svg',
    DDB: 'icons/dynamodb.svg',
    Cache: 'icons/elasticache.svg',
    S3: 'icons/s3.svg',
    ALB: 'icons/alb.svg',
    NLB: 'icons/nlb.svg',
    TG: 'icons/tg.svg',
    SG: 'icons/sg.svg',
    IAM: 'icons/iam.svg',
    KMS: 'icons/kms.svg',
    WAF: 'icons/waf.svg',
    CF: 'icons/cloudfront.svg',
    R53: 'icons/route53.svg',
    SQS: 'icons/sqs.svg',
    SNS: 'icons/sns.svg',
    CW: 'icons/cloudwatch.svg',
    Docker: 'icons/docker.svg',
    TFModule: 'icons/terraform.svg',
    // GCP — official category icons
    GcpVPC:      'gcp_icons/Networking/SVG/Networking-512-color-rgb.svg',
    GcpSubnet:   'gcp_icons/Networking/SVG/Networking-512-color-rgb.svg',
    GcpFW:       'gcp_icons/Security Identity/SVG/SecurityIdentity-512-color.svg',
    GcpRouter:   'gcp_icons/Networking/SVG/Networking-512-color-rgb.svg',
    GcpIP:       'gcp_icons/Networking/SVG/Networking-512-color-rgb.svg',
    GcpGCE:      'gcp_icons/Compute/SVG/Compute-512-color.svg',
    GcpGKE:      'gcp_icons/Containers/SVG/Containers-512-color.svg',
    GcpRun:      'gcp_icons/Serverless Computing/SVG/ServerlessComputing-512-color.svg',
    GcpFn:       'gcp_icons/Serverless Computing/SVG/ServerlessComputing-512-color.svg',
    GcpSQL:      'gcp_icons/Databases/SVG/Databases-512-color.svg',
    GcpBQ:       'gcp_icons/Data Analytics/SVG/DataAnalytics-512-color.svg',
    GcpSpanner:  'gcp_icons/Databases/SVG/Databases-512-color.svg',
    GcpBigtable: 'gcp_icons/Databases/SVG/Databases-512-color.svg',
    GcpFirestore:'gcp_icons/Databases/SVG/Databases-512-color.svg',
    GcpMemstore: 'gcp_icons/Databases/SVG/Databases-512-color.svg',
    GcpGCS:      'gcp_icons/Storage/SVG/Storage-512-color.svg',
    GcpLB:       'gcp_icons/Networking/SVG/Networking-512-color-rgb.svg',
    GcpKMS:      'gcp_icons/Security Identity/SVG/SecurityIdentity-512-color.svg',
    GcpSecret:   'gcp_icons/Security Identity/SVG/SecurityIdentity-512-color.svg',
    GcpSA:       'gcp_icons/Security Identity/SVG/SecurityIdentity-512-color.svg',
    GcpPubSub:   'gcp_icons/Integration Services/SVG/IntegrationServices-512-color.svg',
    GcpDNS:      'gcp_icons/Networking/SVG/Networking-512-color-rgb.svg',
    GcpMon:      'gcp_icons/Observability/SVG/Observability-512-color.svg',
    // Azure
    AzVM: 'icons/az-vm.svg',
    AzVMSS: 'icons/az-vmss.svg',
    AzAKS: 'icons/az-aks.svg',
    AzACI: 'icons/az-aci.svg',
    AzFunc: 'icons/az-function.svg',
    AzApp: 'icons/az-appservice.svg',
    AzAppGW: 'icons/az-appgw.svg',
    AzLB: 'icons/az-lb.svg',
    AzFD: 'icons/az-frontdoor.svg',
    AzTM: 'icons/az-trafficmgr.svg',
    AzSQL: 'icons/az-sql.svg',
    AzCosmos: 'icons/az-cosmos.svg',
    AzPostgres: 'icons/az-postgres.svg',
    AzRedis: 'icons/az-redis.svg',
    AzStorage: 'icons/az-storage.svg',
    AzNSG: 'icons/az-nsg.svg',
    AzKV: 'icons/az-keyvault.svg',
    AzSB: 'icons/az-servicebus.svg',
    AzEH: 'icons/az-eventhub.svg',
    AzDNS: 'icons/az-dns.svg',
    AzMonitor: 'icons/az-monitor.svg',
    AzInsights: 'icons/az-appinsights.svg',
};

// Keep legacy alias so any external code using the old name still works
export const AWS_ICON_PATHS = ICON_PATHS;

export const RESOURCE_CATEGORIES = {
    // ── AWS ──────────────────────────────────────────────────────────────────
    vpc:         { match: ['aws_vpc', 'aws_default_vpc', 'azurerm_virtual_network'], color: '#118ab2', label: 'VPC', icon: 'VPC' },
    subnet:      { match: ['aws_subnet', 'azurerm_subnet'], color: '#073b4c', label: 'Subnet', icon: 'Subnet' },
    instance:    { match: ['aws_instance', 'aws_launch_template'], color: '#ff6b35', label: 'EC2', icon: 'EC2' },
    eks:         { match: ['aws_eks_cluster', 'aws_eks_node_group'], color: '#ff6b35', label: 'EKS', icon: 'EKS' },
    ecs:         { match: ['aws_ecs_cluster', 'aws_ecs_service', 'aws_ecs_task_definition'], color: '#ff6b35', label: 'ECS', icon: 'ECS' },
    lambda:      { match: ['aws_lambda_function'], color: '#ff6b35', label: 'Lambda', icon: 'Lambda' },
    rds:         { match: ['aws_db_instance', 'aws_rds_cluster'], color: '#ef476f', label: 'RDS', icon: 'RDS' },
    dynamodb:    { match: ['aws_dynamodb_table'], color: '#ef476f', label: 'DynamoDB', icon: 'DDB' },
    elasticache: { match: ['aws_elasticache_cluster', 'aws_elasticache_replication_group'], color: '#ef476f', label: 'ElastiCache', icon: 'Cache' },
    s3:          { match: ['aws_s3_bucket'], color: '#ffd166', label: 'S3', icon: 'S3' },
    alb:         { match: ['aws_alb'], color: '#06d6a0', label: 'ALB', icon: 'ALB' },
    nlb:         { match: [], color: '#06d6a0', label: 'NLB', icon: 'NLB' },
    tg:          { match: ['aws_lb_target_group', 'aws_alb_target_group'], color: '#06d6a0', label: 'Target Group', icon: 'TG' },
    sg:          { match: ['aws_security_group'], color: '#8338ec', label: 'Security Group', icon: 'SG' },
    iam_role:    { match: ['aws_iam_role'], color: '#8338ec', label: 'IAM Role', icon: 'IAM' },
    route53:     { match: ['aws_route53_zone', 'aws_route53_record'], color: '#8338ec', label: 'Route 53', icon: 'R53' },
    cloudfront:  { match: ['aws_cloudfront_distribution'], color: '#8338ec', label: 'CloudFront', icon: 'CF' },
    sqs:         { match: ['aws_sqs_queue'], color: '#e07a5f', label: 'SQS', icon: 'SQS' },
    sns:         { match: ['aws_sns_topic'], color: '#e07a5f', label: 'SNS', icon: 'SNS' },
    ecr:         { match: ['aws_ecr_repository'], color: '#ff6b35', label: 'ECR', icon: 'ECR' },
    nat:         { match: ['aws_nat_gateway'], color: '#118ab2', label: 'NAT GW', icon: 'NAT' },
    igw:         { match: ['aws_internet_gateway'], color: '#118ab2', label: 'IGW', icon: 'IGW' },
    eip:         { match: ['aws_eip'], color: '#118ab2', label: 'Elastic IP', icon: 'EIP' },
    kms:         { match: ['aws_kms_key'], color: '#8338ec', label: 'KMS', icon: 'KMS' },
    cloudwatch:  { match: ['aws_cloudwatch_log_group', 'aws_cloudwatch_metric_alarm'], color: '#e07a5f', label: 'CloudWatch', icon: 'CW' },
    autoscaling: { match: ['aws_autoscaling_group'], color: '#ff6b35', label: 'ASG', icon: 'ASG' },
    waf:          { match: ['aws_wafv2_web_acl'], color: '#8338ec', label: 'WAF', icon: 'WAF' },
    route_table:  { match: ['aws_route_table', 'aws_route_table_association', 'aws_main_route_table_association'], color: '#118ab2', label: 'Route Table', icon: 'IGW' },
    transit_gw:   { match: ['aws_transit_gateway', 'aws_transit_gateway_attachment', 'aws_transit_gateway_vpc_attachment'], color: '#118ab2', label: 'Transit GW', icon: 'VPC' },
    vpn_gw:       { match: ['aws_vpn_gateway', 'aws_vpn_connection', 'aws_customer_gateway'], color: '#118ab2', label: 'VPN GW', icon: 'IGW' },
    network_iface: { match: ['aws_network_interface', 'aws_network_interface_attachment'], color: '#118ab2', label: 'Network IF', icon: 'EIP' },
    // ── Azure ────────────────────────────────────────────────────────────────
    az_vm:       { match: ['azurerm_virtual_machine', 'azurerm_linux_virtual_machine', 'azurerm_windows_virtual_machine'], color: '#0078D4', label: 'VM', icon: 'AzVM' },
    az_vmss:     { match: ['azurerm_virtual_machine_scale_set', 'azurerm_linux_virtual_machine_scale_set', 'azurerm_windows_virtual_machine_scale_set'], color: '#0078D4', label: 'Scale Set', icon: 'AzVMSS' },
    az_aks:      { match: ['azurerm_kubernetes_cluster'], color: '#0078D4', label: 'AKS', icon: 'AzAKS' },
    az_aci:      { match: ['azurerm_container_group'], color: '#0078D4', label: 'Container', icon: 'AzACI' },
    az_function: { match: ['azurerm_function_app', 'azurerm_linux_function_app', 'azurerm_windows_function_app'], color: '#0078D4', label: 'Functions', icon: 'AzFunc' },
    az_appservice: { match: ['azurerm_app_service', 'azurerm_linux_web_app', 'azurerm_windows_web_app'], color: '#0078D4', label: 'App Service', icon: 'AzApp' },
    az_appgw:    { match: ['azurerm_application_gateway'], color: '#0072C6', label: 'App Gateway', icon: 'AzAppGW' },
    az_lb:       { match: ['azurerm_lb'], color: '#0072C6', label: 'Load Balancer', icon: 'AzLB' },
    az_frontdoor: { match: ['azurerm_frontdoor', 'azurerm_cdn_frontdoor_profile'], color: '#0072C6', label: 'Front Door', icon: 'AzFD' },
    az_trafficmgr: { match: ['azurerm_traffic_manager_profile'], color: '#0072C6', label: 'Traffic Mgr', icon: 'AzTM' },
    az_sql:      { match: ['azurerm_sql_server', 'azurerm_mssql_server', 'azurerm_sql_database', 'azurerm_mssql_database'], color: '#005BA1', label: 'SQL', icon: 'AzSQL' },
    az_cosmos:   { match: ['azurerm_cosmosdb_account'], color: '#005BA1', label: 'Cosmos DB', icon: 'AzCosmos' },
    az_postgres: { match: ['azurerm_postgresql_server', 'azurerm_postgresql_flexible_server'], color: '#005BA1', label: 'PostgreSQL', icon: 'AzPostgres' },
    az_redis:    { match: ['azurerm_redis_cache'], color: '#005BA1', label: 'Redis Cache', icon: 'AzRedis' },
    az_storage:  { match: ['azurerm_storage_account'], color: '#005BA1', label: 'Storage', icon: 'AzStorage' },
    az_nsg:      { match: ['azurerm_network_security_group'], color: '#6B4C9A', label: 'NSG', icon: 'AzNSG' },
    az_keyvault: { match: ['azurerm_key_vault'], color: '#6B4C9A', label: 'Key Vault', icon: 'AzKV' },
    az_servicebus: { match: ['azurerm_servicebus_namespace'], color: '#e07a5f', label: 'Service Bus', icon: 'AzSB' },
    az_eventhub: { match: ['azurerm_eventhub_namespace'], color: '#e07a5f', label: 'Event Hub', icon: 'AzEH' },
    az_dns:      { match: ['azurerm_dns_zone', 'azurerm_private_dns_zone'], color: '#6B4C9A', label: 'DNS Zone', icon: 'AzDNS' },
    az_monitor:  { match: ['azurerm_log_analytics_workspace', 'azurerm_monitor_action_group'], color: '#e07a5f', label: 'Monitor', icon: 'AzMonitor' },
    az_appinsights: { match: ['azurerm_application_insights'], color: '#e07a5f', label: 'App Insights', icon: 'AzInsights' },
    // ── GCP ──────────────────────────────────────────────────────────────────
    gcp_vpc:       { match: ['google_compute_network'], color: '#1A73E8', label: 'VPC Network', icon: 'GcpVPC' },
    gcp_subnet:    { match: ['google_compute_subnetwork'], color: '#4285F4', label: 'Subnet', icon: 'GcpSubnet' },
    gcp_fw:        { match: ['google_compute_firewall'], color: '#EA4335', label: 'Firewall', icon: 'GcpFW' },
    gcp_router:    { match: ['google_compute_router'], color: '#1A73E8', label: 'Cloud Router', icon: 'GcpRouter' },
    gcp_ip:        { match: ['google_compute_address', 'google_compute_global_address'], color: '#4285F4', label: 'External IP', icon: 'GcpIP' },
    gcp_gce:       { match: ['google_compute_instance', 'google_compute_instance_template', 'google_compute_instance_group', 'google_compute_autoscaler'], color: '#4285F4', label: 'Compute', icon: 'GcpGCE' },
    gcp_gke:       { match: ['google_container_cluster', 'google_container_node_pool'], color: '#1A73E8', label: 'GKE', icon: 'GcpGKE' },
    gcp_run:       { match: ['google_cloud_run_service', 'google_cloud_run_v2_service'], color: '#1A73E8', label: 'Cloud Run', icon: 'GcpRun' },
    gcp_fn:        { match: ['google_cloudfunctions_function', 'google_cloudfunctions2_function'], color: '#FF6D00', label: 'Functions', icon: 'GcpFn' },
    gcp_sql:       { match: ['google_sql_database_instance'], color: '#1A73E8', label: 'Cloud SQL', icon: 'GcpSQL' },
    gcp_bq:        { match: ['google_bigquery_dataset', 'google_bigquery_table'], color: '#4285F4', label: 'BigQuery', icon: 'GcpBQ' },
    gcp_spanner:   { match: ['google_spanner_instance'], color: '#34A853', label: 'Spanner', icon: 'GcpSpanner' },
    gcp_bigtable:  { match: ['google_bigtable_instance'], color: '#34A853', label: 'Bigtable', icon: 'GcpBigtable' },
    gcp_firestore: { match: ['google_firestore_document', 'google_firestore_index'], color: '#FF6D00', label: 'Firestore', icon: 'GcpFirestore' },
    gcp_memstore:  { match: ['google_redis_instance', 'google_memcache_instance'], color: '#34A853', label: 'Memorystore', icon: 'GcpMemstore' },
    gcp_gcs:       { match: ['google_storage_bucket'], color: '#FF8F00', label: 'Cloud Storage', icon: 'GcpGCS' },
    gcp_lb:        { match: ['google_compute_global_forwarding_rule', 'google_compute_forwarding_rule', 'google_compute_backend_service', 'google_compute_url_map'], color: '#34A853', label: 'Load Balancer', icon: 'GcpLB' },
    gcp_kms:       { match: ['google_kms_key_ring', 'google_kms_crypto_key'], color: '#7C4DFF', label: 'KMS', icon: 'GcpKMS' },
    gcp_secret:    { match: ['google_secret_manager_secret'], color: '#7C4DFF', label: 'Secret Manager', icon: 'GcpSecret' },
    gcp_sa:        { match: ['google_service_account'], color: '#7C4DFF', label: 'Service Account', icon: 'GcpSA' },
    gcp_pubsub:    { match: ['google_pubsub_topic', 'google_pubsub_subscription'], color: '#FF6D00', label: 'Pub/Sub', icon: 'GcpPubSub' },
    gcp_dns:       { match: ['google_dns_managed_zone'], color: '#1A73E8', label: 'Cloud DNS', icon: 'GcpDNS' },
    gcp_mon:       { match: ['google_monitoring_alert_policy', 'google_logging_metric', 'google_logging_project_sink'], color: '#FBBC04', label: 'Monitoring', icon: 'GcpMon' },
    // ── Terraform Modules & Terragrunt ────────────────────────────────────────
    tf_module: { match: ['tf_module'], color: '#7B42BC', label: 'Module', icon: 'TFModule' },
    tg_unit:   { match: ['tg_unit'],   color: '#00BEF3', label: 'TG Unit', icon: 'TFModule' },
    // ── Kubernetes ────────────────────────────────────────────────────────────
    k8s_ns:         { match: ['k8s_ns'],         color: '#326CE5', label: 'Namespace',    icon: 'VPC'    },
    k8s_deployment: { match: ['k8s_deployment'], color: '#326CE5', label: 'Deployment',   icon: 'EKS'    },
    k8s_statefulset:{ match: ['k8s_statefulset'],color: '#5C6BC0', label: 'StatefulSet',  icon: 'EKS'    },
    k8s_daemonset:  { match: ['k8s_daemonset'],  color: '#5C6BC0', label: 'DaemonSet',    icon: 'EKS'    },
    k8s_job:        { match: ['k8s_job'],        color: '#5C6BC0', label: 'Job',          icon: 'Lambda' },
    k8s_cronjob:    { match: ['k8s_cronjob'],    color: '#5C6BC0', label: 'CronJob',      icon: 'Lambda' },
    k8s_service:    { match: ['k8s_service'],    color: '#0097A7', label: 'Service',      icon: 'ALB'    },
    k8s_ingress:    { match: ['k8s_ingress'],    color: '#00838F', label: 'Ingress',      icon: 'IGW'    },
    k8s_configmap:  { match: ['k8s_configmap'],  color: '#7B42BC', label: 'ConfigMap',    icon: 'TFModule'},
    k8s_secret:     { match: ['k8s_secret'],     color: '#7B42BC', label: 'Secret',       icon: 'KMS'    },
    k8s_pvc:        { match: ['k8s_pvc'],        color: '#e07a5f', label: 'PVC',          icon: 'S3'     },
    k8s_pv:         { match: ['k8s_pv'],         color: '#e07a5f', label: 'PersistVolume',icon: 'S3'     },
    k8s_sa:         { match: ['k8s_sa'],         color: '#8338ec', label: 'ServiceAccount',icon:'IAM'    },
    k8s_hpa:        { match: ['k8s_hpa'],        color: '#326CE5', label: 'HPA',          icon: 'ASG'    },
    k8s_netpol:     { match: ['k8s_netpol'],     color: '#8338ec', label: 'NetworkPolicy', icon: 'SG'    },
};

export const CATEGORY_GROUPS = {
    INTERNET:  new Set(['igw', 'cloudfront', 'route53', 'waf', 'transit_gw', 'vpn_gw', 'az_frontdoor', 'az_dns', 'az_trafficmgr', 'gcp_dns', 'gcp_ip', 'k8s_ingress']),
    INGRESS:   new Set(['alb', 'nlb', 'tg', 'az_appgw', 'az_lb', 'gcp_lb', 'k8s_service']),
    DATA:      new Set(['rds', 'dynamodb', 'elasticache', 's3', 'az_sql', 'az_cosmos', 'az_postgres', 'az_redis', 'az_storage', 'gcp_sql', 'gcp_bq', 'gcp_spanner', 'gcp_bigtable', 'gcp_firestore', 'gcp_memstore', 'gcp_gcs', 'k8s_pvc', 'k8s_pv']),
    MESSAGING: new Set(['sqs', 'sns', 'az_servicebus', 'az_eventhub', 'gcp_pubsub']),
    SECURITY:  new Set(['sg', 'iam_role', 'kms', 'cloudwatch', 'az_nsg', 'az_keyvault', 'az_monitor', 'az_appinsights', 'gcp_fw', 'gcp_kms', 'gcp_secret', 'gcp_sa', 'gcp_mon', 'k8s_secret', 'k8s_netpol', 'k8s_sa', 'k8s_configmap']),
    VPC:       new Set(['vpc', 'gcp_vpc', 'k8s_ns']),
    SUBNET:    new Set(['subnet', 'gcp_subnet']),
};

export const STAT_CATEGORY_MAP = {
    vpc:     ['vpc', 'subnet', 'nat', 'igw', 'eip', 'route_table', 'transit_gw', 'vpn_gw', 'network_iface', 'gcp_vpc', 'gcp_subnet', 'gcp_router', 'k8s_ns'],
    compute: ['instance', 'eks', 'ecs', 'lambda', 'ecr', 'autoscaling', 'az_vm', 'az_vmss', 'az_aks', 'az_aci', 'az_function', 'az_appservice', 'gcp_gce', 'gcp_gke', 'gcp_run', 'gcp_fn', 'k8s_deployment', 'k8s_statefulset', 'k8s_daemonset', 'k8s_job', 'k8s_cronjob', 'k8s_hpa'],
    db:      ['rds', 'dynamodb', 'elasticache', 'az_sql', 'az_cosmos', 'az_postgres', 'az_redis', 'gcp_sql', 'gcp_bq', 'gcp_spanner', 'gcp_bigtable', 'gcp_firestore', 'gcp_memstore'],
    storage: ['s3', 'az_storage', 'gcp_gcs', 'k8s_pvc', 'k8s_pv'],
    lb:      ['alb', 'nlb', 'tg', 'az_appgw', 'az_lb', 'az_frontdoor', 'az_trafficmgr', 'gcp_lb', 'k8s_service', 'k8s_ingress'],
};

export const SVG_LAYOUT = {
    NW: 120,
    NH: 76,
    NGX: 20,
    NGY: 16,
    ICON_S: 34,
    CP: 40,
    VPC_LBL: 34,
    VPC_PAD: 22,
    SUB_LBL: 26,
    SUB_PAD: 14,
    SUB_GAP: 12,
    ZONE_GAP: 20,
    SEC_GAP: 20,
    maxIngressCols: 6,
    maxDataCols: 6,
    maxOtherCols: 4,
    maxInternetCols: 6,
    maxMessagingCols: 6,
    maxSubnetCols: 3,
};

export const DRAWIO_LAYOUT = {
    NW: 78,
    NH: 78,
    NGX: 32,
    NGY: 32,
    ICON_S: 0,
    CP: 50,
    VPC_LBL: 60,
    VPC_PAD: 40,
    SUB_LBL: 50,
    SUB_PAD: 28,
    SUB_GAP: 16,
    ZONE_GAP: 40,
    SEC_GAP: 40,
    maxIngressCols: 5,
    maxDataCols: 5,
    maxOtherCols: 4,
    maxInternetCols: 6,
    maxMessagingCols: 5,
    maxSubnetCols: 3,
};
