export const SVG_NS = 'http://www.w3.org/2000/svg';
export const XLINK_NS = 'http://www.w3.org/1999/xlink';

export const ICON_PATHS = {
    // AWS
    EC2: 'icons/ec2.svg',
    EKS: 'icons/eks.svg',
    ECS: 'icons/ecs.svg',
    Lambda: 'icons/lambda.svg',
    ASG: 'icons/autoscaling.svg',
    ECR: 'icons/ecr.svg',
    VPC: 'icons/vpc.svg',
    Subnet: 'icons/subnet.svg',
    IGW: 'icons/igw.svg',
    NAT: 'icons/nat.svg',
    EIP: 'icons/eip.svg',
    RDS: 'icons/rds.svg',
    DDB: 'icons/dynamodb.svg',
    Cache: 'icons/elasticache.svg',
    S3: 'icons/s3.svg',
    ALB: 'icons/alb.svg',
    NLB: 'icons/nlb.svg',
    TG: 'icons/tg.svg',
    SG: 'icons/sg.svg',
    IAM: 'icons/iam.svg',
    KMS: 'icons/kms.svg',
    WAF: 'icons/waf.svg',
    CF: 'icons/cloudfront.svg',
    R53: 'icons/route53.svg',
    SQS: 'icons/sqs.svg',
    SNS: 'icons/sns.svg',
    CW: 'icons/cloudwatch.svg',
    Docker: 'icons/docker.svg',
    // Azure
    AzVM: 'icons/az-vm.svg',
    AzVMSS: 'icons/az-vmss.svg',
    AzAKS: 'icons/az-aks.svg',
    AzACI: 'icons/az-aci.svg',
    AzFunc: 'icons/az-function.svg',
    AzApp: 'icons/az-appservice.svg',
    AzAppGW: 'icons/az-appgw.svg',
    AzLB: 'icons/az-lb.svg',
    AzFD: 'icons/az-frontdoor.svg',
    AzTM: 'icons/az-trafficmgr.svg',
    AzSQL: 'icons/az-sql.svg',
    AzCosmos: 'icons/az-cosmos.svg',
    AzPostgres: 'icons/az-postgres.svg',
    AzRedis: 'icons/az-redis.svg',
    AzStorage: 'icons/az-storage.svg',
    AzNSG: 'icons/az-nsg.svg',
    AzKV: 'icons/az-keyvault.svg',
    AzSB: 'icons/az-servicebus.svg',
    AzEH: 'icons/az-eventhub.svg',
    AzDNS: 'icons/az-dns.svg',
    AzMonitor: 'icons/az-monitor.svg',
    AzInsights: 'icons/az-appinsights.svg',
};

// Keep legacy alias so any external code using the old name still works
export const AWS_ICON_PATHS = ICON_PATHS;

export const RESOURCE_CATEGORIES = {
    // ── AWS ──────────────────────────────────────────────────────────────────
    vpc:         { match: ['aws_vpc', 'aws_default_vpc', 'azurerm_virtual_network'], color: '#118ab2', label: 'VPC', icon: 'VPC' },
    subnet:      { match: ['aws_subnet', 'azurerm_subnet'], color: '#073b4c', label: 'Subnet', icon: 'Subnet' },
    instance:    { match: ['aws_instance', 'aws_launch_template'], color: '#ff6b35', label: 'EC2', icon: 'EC2' },
    eks:         { match: ['aws_eks_cluster', 'aws_eks_node_group'], color: '#ff6b35', label: 'EKS', icon: 'EKS' },
    ecs:         { match: ['aws_ecs_cluster', 'aws_ecs_service', 'aws_ecs_task_definition'], color: '#ff6b35', label: 'ECS', icon: 'ECS' },
    lambda:      { match: ['aws_lambda_function'], color: '#ff6b35', label: 'Lambda', icon: 'Lambda' },
    rds:         { match: ['aws_db_instance', 'aws_rds_cluster'], color: '#ef476f', label: 'RDS', icon: 'RDS' },
    dynamodb:    { match: ['aws_dynamodb_table'], color: '#ef476f', label: 'DynamoDB', icon: 'DDB' },
    elasticache: { match: ['aws_elasticache_cluster', 'aws_elasticache_replication_group'], color: '#ef476f', label: 'ElastiCache', icon: 'Cache' },
    s3:          { match: ['aws_s3_bucket'], color: '#ffd166', label: 'S3', icon: 'S3' },
    alb:         { match: ['aws_alb'], color: '#06d6a0', label: 'ALB', icon: 'ALB' },
    nlb:         { match: [], color: '#06d6a0', label: 'NLB', icon: 'NLB' },
    tg:          { match: ['aws_lb_target_group', 'aws_alb_target_group'], color: '#06d6a0', label: 'Target Group', icon: 'TG' },
    sg:          { match: ['aws_security_group'], color: '#8338ec', label: 'Security Group', icon: 'SG' },
    iam_role:    { match: ['aws_iam_role'], color: '#8338ec', label: 'IAM Role', icon: 'IAM' },
    route53:     { match: ['aws_route53_zone', 'aws_route53_record'], color: '#8338ec', label: 'Route 53', icon: 'R53' },
    cloudfront:  { match: ['aws_cloudfront_distribution'], color: '#8338ec', label: 'CloudFront', icon: 'CF' },
    sqs:         { match: ['aws_sqs_queue'], color: '#e07a5f', label: 'SQS', icon: 'SQS' },
    sns:         { match: ['aws_sns_topic'], color: '#e07a5f', label: 'SNS', icon: 'SNS' },
    ecr:         { match: ['aws_ecr_repository'], color: '#ff6b35', label: 'ECR', icon: 'ECR' },
    nat:         { match: ['aws_nat_gateway'], color: '#118ab2', label: 'NAT GW', icon: 'NAT' },
    igw:         { match: ['aws_internet_gateway'], color: '#118ab2', label: 'IGW', icon: 'IGW' },
    eip:         { match: ['aws_eip'], color: '#118ab2', label: 'Elastic IP', icon: 'EIP' },
    kms:         { match: ['aws_kms_key'], color: '#8338ec', label: 'KMS', icon: 'KMS' },
    cloudwatch:  { match: ['aws_cloudwatch_log_group', 'aws_cloudwatch_metric_alarm'], color: '#e07a5f', label: 'CloudWatch', icon: 'CW' },
    autoscaling: { match: ['aws_autoscaling_group'], color: '#ff6b35', label: 'ASG', icon: 'ASG' },
    waf:         { match: ['aws_wafv2_web_acl'], color: '#8338ec', label: 'WAF', icon: 'WAF' },
    // ── Azure ────────────────────────────────────────────────────────────────
    az_vm:       { match: ['azurerm_virtual_machine', 'azurerm_linux_virtual_machine', 'azurerm_windows_virtual_machine'], color: '#0078D4', label: 'VM', icon: 'AzVM' },
    az_vmss:     { match: ['azurerm_virtual_machine_scale_set', 'azurerm_linux_virtual_machine_scale_set', 'azurerm_windows_virtual_machine_scale_set'], color: '#0078D4', label: 'Scale Set', icon: 'AzVMSS' },
    az_aks:      { match: ['azurerm_kubernetes_cluster'], color: '#0078D4', label: 'AKS', icon: 'AzAKS' },
    az_aci:      { match: ['azurerm_container_group'], color: '#0078D4', label: 'Container', icon: 'AzACI' },
    az_function: { match: ['azurerm_function_app', 'azurerm_linux_function_app', 'azurerm_windows_function_app'], color: '#0078D4', label: 'Functions', icon: 'AzFunc' },
    az_appservice: { match: ['azurerm_app_service', 'azurerm_linux_web_app', 'azurerm_windows_web_app'], color: '#0078D4', label: 'App Service', icon: 'AzApp' },
    az_appgw:    { match: ['azurerm_application_gateway'], color: '#0072C6', label: 'App Gateway', icon: 'AzAppGW' },
    az_lb:       { match: ['azurerm_lb'], color: '#0072C6', label: 'Load Balancer', icon: 'AzLB' },
    az_frontdoor: { match: ['azurerm_frontdoor', 'azurerm_cdn_frontdoor_profile'], color: '#0072C6', label: 'Front Door', icon: 'AzFD' },
    az_trafficmgr: { match: ['azurerm_traffic_manager_profile'], color: '#0072C6', label: 'Traffic Mgr', icon: 'AzTM' },
    az_sql:      { match: ['azurerm_sql_server', 'azurerm_mssql_server', 'azurerm_sql_database', 'azurerm_mssql_database'], color: '#005BA1', label: 'SQL', icon: 'AzSQL' },
    az_cosmos:   { match: ['azurerm_cosmosdb_account'], color: '#005BA1', label: 'Cosmos DB', icon: 'AzCosmos' },
    az_postgres: { match: ['azurerm_postgresql_server', 'azurerm_postgresql_flexible_server'], color: '#005BA1', label: 'PostgreSQL', icon: 'AzPostgres' },
    az_redis:    { match: ['azurerm_redis_cache'], color: '#005BA1', label: 'Redis Cache', icon: 'AzRedis' },
    az_storage:  { match: ['azurerm_storage_account'], color: '#005BA1', label: 'Storage', icon: 'AzStorage' },
    az_nsg:      { match: ['azurerm_network_security_group'], color: '#6B4C9A', label: 'NSG', icon: 'AzNSG' },
    az_keyvault: { match: ['azurerm_key_vault'], color: '#6B4C9A', label: 'Key Vault', icon: 'AzKV' },
    az_servicebus: { match: ['azurerm_servicebus_namespace'], color: '#e07a5f', label: 'Service Bus', icon: 'AzSB' },
    az_eventhub: { match: ['azurerm_eventhub_namespace'], color: '#e07a5f', label: 'Event Hub', icon: 'AzEH' },
    az_dns:      { match: ['azurerm_dns_zone', 'azurerm_private_dns_zone'], color: '#6B4C9A', label: 'DNS Zone', icon: 'AzDNS' },
    az_monitor:  { match: ['azurerm_log_analytics_workspace', 'azurerm_monitor_action_group'], color: '#e07a5f', label: 'Monitor', icon: 'AzMonitor' },
    az_appinsights: { match: ['azurerm_application_insights'], color: '#e07a5f', label: 'App Insights', icon: 'AzInsights' },
};

export const CATEGORY_GROUPS = {
    INTERNET:  new Set(['igw', 'cloudfront', 'route53', 'waf', 'az_frontdoor', 'az_dns', 'az_trafficmgr']),
    INGRESS:   new Set(['alb', 'nlb', 'tg', 'az_appgw', 'az_lb']),
    DATA:      new Set(['rds', 'dynamodb', 'elasticache', 's3', 'az_sql', 'az_cosmos', 'az_postgres', 'az_redis', 'az_storage']),
    MESSAGING: new Set(['sqs', 'sns', 'az_servicebus', 'az_eventhub']),
    SECURITY:  new Set(['sg', 'iam_role', 'kms', 'cloudwatch', 'az_nsg', 'az_keyvault', 'az_monitor', 'az_appinsights']),
    VPC:       new Set(['vpc']),
    SUBNET:    new Set(['subnet']),
};

export const STAT_CATEGORY_MAP = {
    vpc:     ['vpc', 'subnet', 'nat', 'igw', 'eip'],
    compute: ['instance', 'eks', 'ecs', 'lambda', 'ecr', 'autoscaling', 'az_vm', 'az_vmss', 'az_aks', 'az_aci', 'az_function', 'az_appservice'],
    db:      ['rds', 'dynamodb', 'elasticache', 'az_sql', 'az_cosmos', 'az_postgres', 'az_redis'],
    storage: ['s3', 'az_storage'],
    lb:      ['alb', 'nlb', 'tg', 'az_appgw', 'az_lb', 'az_frontdoor', 'az_trafficmgr'],
};

export const SVG_LAYOUT = {
    NW: 120,
    NH: 76,
    NGX: 20,
    NGY: 16,
    ICON_S: 34,
    CP: 40,
    VPC_LBL: 34,
    VPC_PAD: 22,
    SUB_LBL: 26,
    SUB_PAD: 14,
    SUB_GAP: 12,
    ZONE_GAP: 20,
    SEC_GAP: 20,
    maxIngressCols: 6,
    maxDataCols: 6,
    maxOtherCols: 4,
    maxInternetCols: 6,
    maxMessagingCols: 6,
    maxSubnetCols: 3,
};

export const DRAWIO_LAYOUT = {
    NW: 78,
    NH: 78,
    NGX: 32,
    NGY: 32,
    ICON_S: 0,
    CP: 50,
    VPC_LBL: 60,
    VPC_PAD: 40,
    SUB_LBL: 50,
    SUB_PAD: 28,
    SUB_GAP: 16,
    ZONE_GAP: 40,
    SEC_GAP: 40,
    maxIngressCols: 5,
    maxDataCols: 5,
    maxOtherCols: 4,
    maxInternetCols: 6,
    maxMessagingCols: 5,
    maxSubnetCols: 3,
};
